#!/usr/bin/env bun
/**
 * Generate `src/versions.ts` from the current workspace package.json files.
 * Runs as `prebuild` so `workkit init` scaffolds projects pinned to the
 * versions shipped with the CLI build — not a loose `"latest"` that breaks
 * reproducibility and yanks users across breaking releases.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..", "..");
const PACKAGES = join(ROOT, "packages");
const OUT = resolve(__dirname, "..", "src", "versions.ts");

interface PackageJson {
	name?: string;
	version?: string;
	private?: boolean;
}

const versions: Record<string, string> = {};
for (const entry of readdirSync(PACKAGES, { withFileTypes: true })) {
	if (!entry.isDirectory()) continue;
	const pkgPath = join(PACKAGES, entry.name, "package.json");
	try {
		const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as PackageJson;
		if (pkg.private) continue;
		if (!pkg.name || !pkg.version) continue;
		if (!pkg.name.startsWith("@workkit/")) continue;
		versions[pkg.name] = `^${pkg.version}`;
	} catch {
		// Skip unreadable or missing package.json
	}
}

const sortedKeys = Object.keys(versions).sort();
const entries = sortedKeys.map((k) => `\t${JSON.stringify(k)}: ${JSON.stringify(versions[k])},`);
const content = `// Auto-generated by scripts/sync-versions.ts — do not edit by hand.
// Refreshed on every CLI build (prebuild hook) so \`workkit init\` scaffolds
// projects pinned to the versions shipped with this CLI build.
export const WORKKIT_VERSIONS: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(OUT, content);
console.log(`[sync-versions] wrote ${sortedKeys.length} package versions to ${OUT}`);
